spring.application.name=jeevanandham.subscription
spring.datasource.url=jdbc:mysql://localhost:3306/subscription_app?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate manages the schema during early local development.
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
